name: SkillsTracker CI
run-name: ${{ github.head_ref }} ${{ github.sha }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    if: '! github.event.pull_request.draft'
    uses: ./.github/workflows/run-tests.yml
